### ISSUE TITLE
NFT whitelisting

### ISSUE THREAD

**Issue by NNKKA** [atom-dao/NFT-whitelisting#1]
submit the links to the repository. Winner gets INR 1500.

**Comment by FibrinLab** [comment]
https://github.com/FibrinLab/NFT-Whitelist

**Comment by mecskyverse** [comment]
NFT WhiteListing Merkle Tree Project 

https://github.com/mecskyverse/Merkle-Tree-NFT.git

My first submission for Atom DAO Bounty 

Do check it out and a review would be very helpfull

**Comment by NNKKA** [comment]
> https://github.com/FibrinLab/NFT-Whitelist

can you please add a readme.md file

**Comment by NNKKA** [comment]
> NFT WhiteListing Merkle Tree Project
> 
> https://github.com/mecskyverse/Merkle-Tree-NFT.git
> 
> My first submission for Atom DAO Bounty
> 
> Do check it out and a review would be very helpfull

your submission is too complicated can you maybe simplify this with minimalistic features and make another submission

**Comment by mecskyverse** [comment]
> > NFT WhiteListing Merkle Tree Project
> > https://github.com/mecskyverse/Merkle-Tree-NFT.git
> > My first submission for Atom DAO Bounty
> > Do check it out and a review would be very helpful
> 
> your submission is too complicated can you maybe simplify this with minimalistic features and make another submission


Yes, I understand I was just loving the project so made a full dapp for practising. Anyway, I will do it, but will the new submission be eligible or not as the deadline has already passed?

**Comment by NNKKA** [comment]
it will be eligible if you send it by tonight

**Comment by NNKKA** [comment]
> > > NFT WhiteListing Merkle Tree Project
> > > https://github.com/mecskyverse/Merkle-Tree-NFT.git
> > > My first submission for Atom DAO Bounty
> > > Do check it out and a review would be very helpful
> > 
> > 
> > your submission is too complicated can you maybe simplify this with minimalistic features and make another submission
> 
> Yes, I understand I was just loving the project so made a full dapp for practising. Anyway, I will do it, but will the new submission be eligible or not as the deadline has already passed?

if you make a simplistic version that extracts the merkleproof into the frontend for any given address and then use that to mint a NFT then you will be declared winner or else we will be closing the issue without any winners

**Comment by mecskyverse** [comment]
> > > > NFT WhiteListing Merkle Tree Project
> > > > https://github.com/mecskyverse/Merkle-Tree-NFT.git
> > > > My first submission for Atom DAO Bounty
> > > > Do check it out and a review would be very helpful
> > > 
> > > 
> > > your submission is too complicated can you maybe simplify this with minimalistic features and make another submission
> > 
> > 
> > Yes, I understand I was just loving the project so made a full dapp for practising. Anyway, I will do it, but will the new submission be eligible or not as the deadline has already passed?
> 
> if you make a simplistic version that extracts the merkleproof into the frontend for any given address and then use that to mint a NFT then you will be declared winner or else we will be closing the issue without any winners


Here is the simpler version of it I have not used any testnet or metamask in it you can just interact with it through Remix and Ide.
https://github.com/mecskyverse/NFT-WhiteList-Simple.git
